image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:

    - main # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-deadline.jar -P:jdbc.url=jdbc:mysql://localhost:3306/app-db -P:jdbc.user=app-line -P:jdbc.password=12345 &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true  # запускаем тест, флаг --info позволяет выводить больше информации
